# Generated by Django 3.2.6 on 2022-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'inactive')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
